import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import Sidebar from '../components/Sidebar';
import Header from '../components/Header';
import Footer from '../components/Footer';

export default function PrivacyPolicy() {
  const navigate = useNavigate();
  const [role, setRole] = useState('officer');

  useEffect(() => {
    const savedUser = localStorage.getItem('urbanSyncUser');
    if (!savedUser) {
      navigate('/login');
      return;
    }
    const user = JSON.parse(savedUser);
    setRole(user.role);
  }, [navigate]);

  return (
    <div className="flex h-screen bg-[#F8FAFC] font-sans overflow-hidden">
      <Sidebar role={role} />

      <div className="flex-1 flex flex-col h-full overflow-hidden">
        <Header breadcrumbs={['Legal', 'Privacy Policy']} />

        <main className="flex-1 overflow-y-auto p-8 flex flex-col">
          <div className="max-w-4xl mx-auto w-full flex-1">
            
            <div className="mb-8">
              <h2 className="text-2xl font-extrabold text-[#1E293B]">Privacy Policy</h2>
              <p className="text-[13px] text-[#64748B] mt-1">Effective Date: January 1, 2026</p>
            </div>

            <div className="bg-white border border-[#E2E8F0] rounded-xl shadow-sm p-8 space-y-8">
              
              <section>
                <h3 className="text-lg font-bold text-[#1E293B] mb-3">1. Information We Collect</h3>
                <p className="text-[13px] text-[#475569] leading-relaxed mb-3">
                  The UrbanSync Portal ("System") collects information necessary to process municipal complaints and manage administrative workflows. This includes:
                </p>
                <ul className="list-disc pl-5 text-[13px] text-[#475569] leading-relaxed space-y-1">
                  <li><strong>Citizen Data:</strong> Names, phone numbers, email addresses, and exact GPS coordinates attached to complaints.</li>
                  <li><strong>Official Data:</strong> Employee ID codes, assigned authorities, and operational logs (e.g., status changes, reassignments).</li>
                  <li><strong>System Data:</strong> IP addresses, login timestamps, and device identifiers used for security auditing.</li>
                </ul>
              </section>

              <section>
                <h3 className="text-lg font-bold text-[#1E293B] mb-3">2. How We Use Your Information</h3>
                <p className="text-[13px] text-[#475569] leading-relaxed">
                  Data collected within the System is strictly utilized for governance and municipal management. Citizen data is shared only with the specific Regional Authority assigned to resolve their complaint. Operational data generated by Officers and Super Admins is utilized to calculate Performance Indices and Resolution Rates for national reporting.
                </p>
              </section>

              <section>
                <h3 className="text-lg font-bold text-[#1E293B] mb-3">3. Data Security & Storage</h3>
                <p className="text-[13px] text-[#475569] leading-relaxed">
                  All system passwords and credentials are cryptographically hashed using standard bcrypt algorithms. Rejection notes and internal metadata are restricted to authorized personnel based on Role-Based Access Control (RBAC). The National Governance Digital Division retains all complaint records indefinitely for public infrastructure auditing.
                </p>
              </section>

              <section>
                <h3 className="text-lg font-bold text-[#1E293B] mb-3">4. Contact Information</h3>
                <p className="text-[13px] text-[#475569] leading-relaxed">
                  For questions regarding data compliance, evidence management, or account deletion requests, please contact your Regional Administrator or email <strong>privacy@urbansync.gov.lk</strong>.
                </p>
              </section>

            </div>
          </div>
          
          <div className="mt-8">
            <Footer />
          </div>
        </main>
      </div>
    </div>
  );
}